spring.application.name=NoPrecinho

#database
spring.datasource.url= jdbc:postgresql://localhost:5432/noprecinho
spring.datasource.jdbc-url=${spring.datasource.url}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.platform=postgres
spring.datasource.username=postgres
spring.datasource.password=Darling2020